metrics:
  - default: cosine.yaml

collectors:
  # - default: SimSiamMultiCollector_l2.yaml
  - default: MultiBranchCollector.yaml

selectors:
  - default: DefaultSelector.yaml

losses:
  - default: MultiPosPairLoss_l2.yaml

models:
  # - trunk: _resnet50_bn.yaml
  - trunk: bninception_bn.yaml
  # consider put proj_bn here
  - embedder: _simsiam_refined_projector.yaml

evaluators:
  - default: Calculator.yaml

# optimizers:
#   - trunk: SGD.yaml
#   - embedder: SGD.yaml
#   - default: SGD_collectors.yaml

optimizers:
  - trunk: AdamW_models.yaml
  - embedder: AdamW_models.yaml
  - default: AdamW_collectors.yaml

schedulers:
  - trunk: step_lr.yaml
  - embedder: step_lr.yaml

gradclipper:
  - trunk: gradclipper_models.yaml
  - embedder: gradclipper_models.yaml
  - default: gradclipper_collectors.yaml

transforms:
  - train: train_crop2_transforms.yaml
  # - train: moco_train_transforms.yaml
  - test: eval_transforms.yaml

datasets:
  - train: imagenet_train.yaml
  - test: imagenet_test.yaml

samplers:
  - train: _MPerClassFullSampler.yaml

collatefns:
  - train: simsiam_multi.yaml

recorders:
  - default: base_recorder.yaml

trainers: 
  - default: BaseTrainer.yaml

testers:
  - default: BaseTester.yaml

managers:
  - default: BaseManager.yaml

LINK_SETTING: 
  to_device_list: [models, collectors, losses]
  to_wrap_list: [models, collectors]

PIPELINE_SETTING:
  - models/trunk/default -> models/embedder/
  - models/embedder/default -> collectors/default/
  - collectors/default/default -> selectors/default/
  - selectors/default/default -> losses/default/
  - losses/default/default -> FINISH/default/loss
