from .simsiam_sup_collector import SimSiamSupCollector
from .simsiam_multi_collector import SimSiamMultiCollector
# from .multi_level_collector_2 import SimSiamMultiCollector
from .multi_branch_collector import MultiBranchCollector